#!/bin/sh
# install.sh — bootstrap the plan.sh CLI + registry onto this machine.
#
# This is the "place the tool on the machine" step. It is DISTINCT from
# "plan.sh install", which renders skills into your coding-agent harnesses.
# No sudo; everything lives under your home by default; idempotent.
set -eu

PROG=install.sh
TOOL=plan.sh

: "${XDG_DATA_HOME:=$HOME/.local/share}"
: "${INSTALL_DIR:=$XDG_DATA_HOME/$TOOL}"
: "${BIN_DIR:=$HOME/.local/bin}"

SRC=''        # resolved source tree (holds plan.sh, registry/, adapters/)
CLEANUP=''    # temp dir to remove on exit, if we extracted a tarball

die() { printf '%s: %s\n' "$PROG" "$*" >&2; exit 1; }
info() { printf '%s: %s\n' "$PROG" "$*"; }
cleanup() { [ -n "$CLEANUP" ] && rm -rf "$CLEANUP" || true; }
trap cleanup EXIT

usage() {
	cat <<EOF
$PROG — install the $TOOL CLI and registry (no sudo, idempotent).

Usage:
  sh $PROG [--uninstall]

Env overrides:
  BIN_DIR              CLI launcher location        (default ~/.local/bin)
  INSTALL_DIR          CLI + registry + adapters    (default \$XDG_DATA_HOME/$TOOL)
  XDG_DATA_HOME        base for default INSTALL_DIR (default ~/.local/share)
  PLAN_SH_SRC          install from this local source tree (skips auto-detect)
  PLAN_SH_TARBALL      install from this local .tar.gz
  PLAN_SH_TARBALL_URL  download and install from this remote .tar.gz

After installing, run "$TOOL install" to render skills into your harnesses.
To remove the tool:  sh $PROG --uninstall
EOF
}

# Resolve a source tree containing plan.sh, registry/, adapters/. Sets SRC.
resolve_src() {
	if [ -n "${PLAN_SH_SRC:-}" ]; then
		SRC="$PLAN_SH_SRC"
		return 0
	fi

	_self=$(CDPATH='' cd -- "$(dirname -- "$0")" 2>/dev/null && pwd || true)
	if [ -n "$_self" ] && [ -f "$_self/$TOOL" ] && [ -d "$_self/registry" ] && [ -d "$_self/adapters" ]; then
		SRC="$_self"
		return 0
	fi

	# No local tree (e.g. piped via curl|sh): fetch/extract a tarball.
	CLEANUP=$(mktemp -d)
	_tb=''
	if [ -n "${PLAN_SH_TARBALL:-}" ]; then
		_tb="$PLAN_SH_TARBALL"
	elif [ -n "${PLAN_SH_TARBALL_URL:-}" ]; then
		_tb="$CLEANUP/src.tar.gz"
		if command -v curl >/dev/null 2>&1; then
			curl -fsSL "$PLAN_SH_TARBALL_URL" -o "$_tb" || die "download failed: $PLAN_SH_TARBALL_URL"
		elif command -v wget >/dev/null 2>&1; then
			wget -qO "$_tb" "$PLAN_SH_TARBALL_URL" || die "download failed: $PLAN_SH_TARBALL_URL"
		else
			die "need curl or wget to download $PLAN_SH_TARBALL_URL"
		fi
	else
		die "cannot locate a $TOOL source tree; run from a clone, or set PLAN_SH_SRC / PLAN_SH_TARBALL / PLAN_SH_TARBALL_URL"
	fi

	[ -f "$_tb" ] || die "tarball not found: $_tb"
	tar -xzf "$_tb" -C "$CLEANUP" || die "failed to extract $_tb"
	if [ -f "$CLEANUP/$TOOL" ] && [ -d "$CLEANUP/registry" ] && [ -d "$CLEANUP/adapters" ]; then
		SRC="$CLEANUP"
		return 0
	fi
	for _d in "$CLEANUP"/*/; do
		if [ -f "${_d}$TOOL" ] && [ -d "${_d}registry" ] && [ -d "${_d}adapters" ]; then
			SRC="${_d%/}"
			return 0
		fi
	done
	die "extracted tarball has no $TOOL source tree (need $TOOL, registry/, adapters/)"
}

do_install() {
	resolve_src
	[ -f "$SRC/$TOOL" ] || die "source tree missing $TOOL: $SRC"
	[ -d "$SRC/registry" ] || die "source tree missing registry/: $SRC"
	[ -d "$SRC/adapters" ] || die "source tree missing adapters/: $SRC"

	mkdir -p "$INSTALL_DIR" "$BIN_DIR"

	# Replace prior registry/adapters wholesale so removed files don't linger.
	rm -rf "$INSTALL_DIR/registry" "$INSTALL_DIR/adapters"
	cp "$SRC/$TOOL" "$INSTALL_DIR/$TOOL"
	cp -R "$SRC/registry" "$INSTALL_DIR/registry"
	cp -R "$SRC/adapters" "$INSTALL_DIR/adapters"
	chmod +x "$INSTALL_DIR/$TOOL"

	# Launcher: a tiny script that points the CLI at its installed data dir.
	_launcher="$BIN_DIR/$TOOL"
	cat > "$_launcher" <<EOF
#!/bin/sh
# $TOOL launcher (generated by $PROG). Points the CLI at its installed data.
PLAN_SH_ROOT='$INSTALL_DIR'
export PLAN_SH_ROOT
exec '$INSTALL_DIR/$TOOL' "\$@"
EOF
	chmod +x "$_launcher"

	info "installed CLI launcher -> $_launcher"
	info "installed tool data    -> $INSTALL_DIR"
	check_path
	info "next: run '$TOOL install' to render skills into your harnesses."
}

check_path() {
	case ":$PATH:" in
		*":$BIN_DIR:"*)
			: ;;
		*)
			info "NOTE: $BIN_DIR is not on your PATH. Add it with:"
			info "  export PATH=\"$BIN_DIR:\$PATH\""
			;;
	esac
}

do_uninstall() {
	_launcher="$BIN_DIR/$TOOL"
	if [ -e "$_launcher" ]; then
		rm -f "$_launcher"
		info "removed CLI launcher $_launcher"
	else
		info "no CLI launcher at $_launcher"
	fi
	if [ -d "$INSTALL_DIR" ]; then
		rm -rf "$INSTALL_DIR"
		info "removed tool data dir $INSTALL_DIR"
	else
		info "no tool data dir at $INSTALL_DIR"
	fi

	# Rendered harness skills + their state are owned by "plan.sh uninstall".
	_state="${XDG_STATE_HOME:-$HOME/.local/state}/$TOOL"
	if [ -f "$_state/state" ]; then
		info "NOTE: rendered harness skills are still installed (tracked in $_state)."
		info "  bootstrap-uninstall does NOT remove them; run '$TOOL uninstall' FIRST to do so."
	fi
	info "bootstrap uninstall complete (rendered harness skills left untouched)."
}

main() {
	case "${1:-}" in
		-h|--help) usage; exit 0 ;;
		--uninstall) do_uninstall; exit 0 ;;
		'') do_install ;;
		*) die "unknown argument '$1' (try --help)" ;;
	esac
}

main "$@"
